[workspace]
members = [
    "programs/fighter_registry",
    "programs/token_economy",
    "programs/marketplace"
]

[provider]
cluster = "devnet"          # or "localnet"
wallet = "/home/abhi/.config/solana/id.json"  # <<- Change to your Solana wallet path!
