[toolchain]

[features]
resolution = true
skip-lint = false
[programs.devnet]
nft_items = "FtJpYaLCQWvwg2h5AQJ9AuEii5ciHTCkLzzhVSjxmtJC"
token_economy = "3UUL22zcovP754udhGLayo7UCdnbHn63S4yWT1oUzMky"
fighter_registry = "8iAqcZnZgfVxSSm8C9UtHadJcSNqvuYaGrQ3XuCnehj7"
marketplace = "BjuQiWyhrmQd3JeWVLbkscM3mYZorti2Y9bDBtLPz4TU"
game_session = "4CWu3JYtBZtqPYsEnPheYt8kipe26gqygUAYiaBicQpD"

[programs.localnet]
nft-items =  "FtJpYaLCQWvwg2h5AQJ9AuEii5ciHTCkLzzhVSjxmtJC"
token_economy = "3UUL22zcovP754udhGLayo7UCdnbHn63S4yWT1oUzMky"
fighter_registry = "8iAqcZnZgfVxSSm8C9UtHadJcSNqvuYaGrQ3XuCnehj7"
marketplace = "BjuQiWyhrmQd3JeWVLbkscM3mYZorti2Y9bDBtLPz4TU"
game_session = "4CWu3JYtBZtqPYsEnPheYt8kipe26gqygUAYiaBicQpD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "programs/fighter_registry", 
    "programs/token_economy", 
    "programs/marketplace", 
    "programs/nft-items", 
    "programs/game_session"
]

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"    # Metaplex Core

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"    # Metaplex Token Metadata

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"    # SPL Token

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"   # Associated Token Account

[[test.validator.clone]]
address = "ComputeBudget111111111111111111111111111111"    # Compute Budget

[[test.validator.clone]]
address = "11111111111111111111111111111111"               # System Program
